# Generated by Django 2.1.2 on 2020-04-30 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[("V", "Valid"), ("I", "Invalid"), ("N", "Neutral")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tolerance", models.FloatField(default=0.5)),
                ("quorum", models.IntegerField(default=10)),
                ("value", models.IntegerField(default=30)),
            ],
            options={"verbose_name_plural": "Criteria"},
        ),
        migrations.CreateModel(
            name="CurrentChallenge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[("V", "Valid"), ("I", "Invalid")], max_length=1
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenge.Challenge",
                    ),
                ),
            ],
        ),
    ]
