# Generated by Django 2.1.2 on 2020-04-30 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="currentchallenge",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="challenge.Challenge"
            ),
        ),
        migrations.AddField(
            model_name="currentchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="criterion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="challenge.Criterion"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exam.Problem"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="currentchallenge", unique_together={("user", "challenge")}
        ),
        migrations.AlterUniqueTogether(
            name="challenge", unique_together={("problem", "criterion")}
        ),
    ]
