# Generated by Django 2.2.10 on 2020-04-30 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exam.Problem"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="problems",
            field=models.ManyToManyField(to="exam.Problem"),
        ),
        migrations.AlterUniqueTogether(
            name="image", unique_together={("name", "problem")}
        ),
    ]
