# Generated by Django 2.2.13 on 2020-07-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("exam", "0002_auto_20200622_0203")]

    operations = [
        migrations.AlterUniqueTogether(
            name="examproblemchoice", unique_together={("problem", "exam")}
        )
    ]
